version: '3.8'
services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - mynetwork
  
  api:
    build: .
    container_name: expressjs_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - mysql_db
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
