apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressjs-api
  template:
    metadata:
      labels:
        app: expressjs-api
    spec:
      initContainers:
        - name: db-check
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-db 3306; do echo "Waiting for database..."; sleep 2; done;']
      containers:
        - name: expressjs-api
          image: sambastraore/my_app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"  
          livenessProbe:
            httpGet:
              path: test/health/live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: test/health/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10  
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_PASSWORD
      restartPolicy: Always
